Iter1 auth
jbakhtin/goph-keeper pull request #1
Opened 2023-12-06 17:20 UTC by jbakhtin

2024-02-08 23:21 UTC, avhitrov requested changes
Несмотря на большое количество файлов, читается код хорошо, что говорит о вдумчивой организации процесса. По реализации замечаний нет. В основном, замечания касаются красоты оформления, из грубых недочетов: ручная подстановка в SQL-код значений вместо писпользования плейсхолдеров. И в принципе, построитель запросов кажется ненужным усложнением, гораздо проще взять готовый (ссылка в коде).

2024-02-08 23:21 UTC, avhitrov commented on cmd/client/main.go
> +		log.Fatal(err)
Не следует во внутренних функциях апеллировать к log.Fatal. Это все-таки очень жесткое прерывание, разрывающее все горутины и отменяющее defer-ы. Тем более, что возвращение ошибки данной функцией все равно наверху приводит к log.Fatal.

Правильное поведение - поднять ошибку как можно выше (при этом можно оборачивать ее на каждом шаге вверх) и там наверху уже решать, что с ней делать.

2024-02-08 23:21 UTC, avhitrov commented on cmd/server/main.go
> +		panic(err)
А вот в данном случае более уместным будет log.Fatal. Во-первых, это самый верхний уровень и никаких деферов и горутин еще не запущено, во-вторых, вручную вызванная паника не очень информативна. И в-третьих, паника куда более полезна, когда не прерывает течение программы, а перехватывается с помощью restore.

2024-02-08 23:21 UTC, avhitrov commented on docs/images/db-structure.jpg
В модели sessions два раза указан refresh_token. Один из них, похоже, должен быть `created_at`.

2024-02-08 23:21 UTC, avhitrov commented on internal/client/application/config/config.go
> +	AppKey string `env:"APP_KEY"`
```suggestion
	appKey string `env:"APP_KEY"`
```
если делаем коннекторы к полю, значит, пытаемся закрыть прямой доступ. А если пытаемся закрыть прямой доступ, то незачем делать поле публичным.

2024-02-08 23:21 UTC, avhitrov commented on internal/client/infrastructure/persistance/grpc/credentials/jwt.go
> +func NewJWTCredentials() credentials.PerRPCCredentials {
```suggestion
func NewJWTCredentials() (credentials.PerRPCCredentials, error) {
```

2024-02-08 23:21 UTC, avhitrov commented on internal/client/infrastructure/persistance/grpc/credentials/jwt.go
> +		log.Fatal(err)
```suggestion
		return jwtCredentials{}, nil
```

2024-02-08 23:21 UTC, avhitrov commented on internal/server/appmodules/README.md
> +По мимо всего каждый модуль построен по принципу гексоганальной архитектуры, что позволяет ему быть максимально независимым
```suggestion
Помимо всего, каждый модуль построен по принципу гексагональной архитектуры, что позволяет ему быть максимально независимым
```
пройдись по комментариям. Опечатки иногда режут глаз.

2024-02-08 23:21 UTC, avhitrov commented on internal/server/appmodules/auth/services/acesstoken/acsesstoken.go
В названиях файлов и каталогов нет однообразия. По-английски слово пишется `access`

2024-02-08 23:21 UTC, avhitrov commented on internal/server/appmodules/auth/services/acesstoken/acsesstoken.go
> +	"github.com/golang-jwt/jwt/v5"
https://t.me/bushigo/27

2024-02-08 23:21 UTC, avhitrov commented on internal/server/storage/postgres/migrations/20231027223251_create_users_table.sql
> +   created_at timestamp NOT NULL,
```suggestion
   created_at timestamp NOT NULL DEFAULT now(),
```
и можно вообще выбросить это поле из всех инсертов.

2024-02-08 23:21 UTC, avhitrov commented on internal/server/storage/postgres/migrations/20231105192721_create_sessions_table.sql
> +    created_at timestamp NOT NULL,
```suggestion
    created_at timestamp NOT NULL DEFAULT now(),
```

2024-02-08 23:21 UTC, avhitrov commented on internal/server/storage/postgres/specifications/basic/and.go
Милая реализация, но при минимальном усложении (понадобятся join-ы, например), все это начнет стремиться к построителю запросов уровня squirrel. Может, уже сразу его задействовать?
https://github.com/Masterminds/squirrel

2024-02-08 23:21 UTC, avhitrov commented on internal/server/storage/postgres/specifications/session/finger_print.go
> +	return fmt.Sprintf("finger_print = %v", s.FingerPrint)
Вообще вставлять любые значения полей в sql-запрос не через плейсхолдер - прямая дорога к sql injection. Даже если код генерится внутри приложения, а не передается снаружи, никто не может гарантировать, что какой-либо из элементов не протащит в себе одинокий апостроф и не обрушит sql-запрос.

2024-02-08 23:21 UTC, avhitrov commented on internal/server/storage/postgres/specifications/session/refresh_token.go
> +	return fmt.Sprintf("refresh_token = '%s'", s.RefreshToken)
Вот так и был в свое время взломан Rambler.

2024-02-08 23:21 UTC, avhitrov commented on internal/server/webserver/grpc/server.go
> +func (s *Server) Shutdown(ctx context.Context) error {
Всегда будет возвращать nil. Необходимо либо отказаться от возвращаемого значения, либо все-таки проверять и возвращать возможные ошибки.

2024-02-09 05:15 UTC, jbakhtin commented on internal/server/storage/postgres/specifications/session/finger_print.go
> +	return fmt.Sprintf("finger_print = %v", s.FingerPrint)
Изначально планировалось реализовать данный построитель запросов именно с использованием плейсхолдеров, по этому интерфейс спецификации содержит `Query()` и `Value()` методы. `Query()`, по задумке, возвращает частичку запроса с плейсхолдером(и), а `Value()` значение(я). Собираться все это должно было при обращении к клиенту базы данных `db.QueryWithContext(ctx, s.Query(), s.Value())`, но при реализации я не принял во внимание особенности драйверов различных БД. Так, например, `mysql` и `postgres` драйвера отличаются тем, что у них в качестве плейсхолдеров используются различные теги, в `mysql` знак вопроса `field = ?`, а в `postgres` нумерация `field = $i`. Написал свою реализацию под знаки вопроса, но когда понял, что это не подходит под изначально выбранную мной Postgres решил сделать такое временное решение: временно засунуть подстановку значений в генерацию запроса, на места плейсхолдеров.

Я посмотрю на Squirrel, спасибо. Но так же хотел подметить то, что моя задача была максимально отделить бизнес слой от технических реализаций. Я попытаюсь оставить бизнес слой с текущими интерфейсами, а на уровне  их реализации подставить генерацию запросов с использованием Squirel, заменив мою самописную реализацию.

2024-02-09 05:25 UTC, jbakhtin commented on internal/server/storage/postgres/specifications/basic/and.go
Понял, изучу этот вопрос.

2024-02-09 05:33 UTC, jbakhtin commented on internal/server/appmodules/auth/services/acesstoken/acsesstoken.go
> +	"github.com/golang-jwt/jwt/v5"
Понял, до этого использовал `goimports` но в этот раз отформатировал все через `gofmt`. Спасибо, посмотрю что есть интересного в `gofumpt`.

2024-02-10 18:22 UTC, jbakhtin commented on internal/server/webserver/grpc/server.go
> +func (s *Server) Shutdown(ctx context.Context) error {
Добавил обработку контекста.

2024-02-12 21:01 UTC, jbakhtin commented on internal/server/storage/postgres/specifications/session/finger_print.go
> +	return fmt.Sprintf("finger_print = %v", s.FingerPrint)
На данный момент не могу с легкостью использовать Squirel пакет в свой реализации. Так же не стал переписывать существующую реализацию на использование плейсхолдеров. 

Изучил проблему sql injection и пока просто обернул подстановку значений в запрос функцией, которая проверят значение на использование в нем всяческих нежелательных символов и табуляций. 

Для этого использовал маленький пакетик https://github.com/feiin/sqlstring

В дальнейшем изучу вопрос подробнее и реализую storage и его адаптеры для бизнес логики более элегантно. Пока, что бы не задерживаться на технических особенностях, перейду к реализации остальной бизнес логики, что бы успеть реализовать mvp.

2024-02-12 21:09 UTC, jbakhtin commented on internal/client/application/config/config.go
> +	AppKey string `env:"APP_KEY"`
хм, немного встал в тупик. Я использую Геттеры для обеспечения контракта между фактическим местом использования конфига и его реализацией. Но, публичные поля в структуре также нужны для возможности парсить в структуру значения по тегам (env, json и тд). Так же изучу этот вопрос более подробнее.

2024-02-12 22:34 UTC, jbakhtin commented
- Прокинул ошибки до верхнего уровня, там где это не было сделано;
- Убрал панику и заменил ее на log.Fatal или os.Exit;
- поправил изображение структуры базы данных (ошибка c дублированием поля `refresh_token`);
- добавил возврат ошибок из функций, там где это требуется;
- исправил опечатки в тексте комментариев, названий файлов и папок;
- отформатировал импорты с помощью `goimports`;
- добавил в создание схемы базы данных `DEFAULT now()` для поля `created_at` и триггеры на `updated_at`;
- добавил обработку значений, для предотвращения sql инъекций, при вставке их в sql запрос;
- добавил обработку контекста в функцию завершения работы сервера;

2024-02-12 22:45 UTC, jbakhtin commented
Ответвляюсь от данного данной ветки на текущем коммите и всю дальнейшую разработку буду вести там, что бы новые наработки, для проверки, не перемешивались с текущими. 

В следующем пул реквесте по мимо основных наработок по бизнес логике добавлю:
- тесты
- документация

2024-02-17 12:51 UTC, avhitrov approved these changes
Все отлично!

2024-02-17 12:51 UTC, avhitrov commented on internal/client/application/config/config.go
> +	AppKey string `env:"APP_KEY"`
Ok, принимается. Не надо ничего менять.

2024-02-17 13:57 UTC, merged